export const products = [
  {
    id: "1",
    productId: "SC-COUPLE-001",
    sku: "SC-COUPLE-001",
    name: "Romantic Couple Stone",
    description: "Celebrate your love with this beautifully crafted stone featuring your favorite couple photo. Hand-polished natural stone with high-definition photo printing. Perfect for anniversaries, Valentine's Day, or as a romantic gift. Each stone is unique with natural variations.",
    price: 699,
    originalPrice: 899,
    rating: 4.8,
    reviews: 124,
    bestseller: true,
    category: "Couple Stones",
    image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400&h=400&fit=crop",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Heart"],
    colors: ["Natural Stone", "Black Marble", "White Marble"],
    stock: 50,
    deliveryDays: 5,
    material: "Natural River Stone",
    weight: "200-500g",
    finish: "Glossy",
  },
  {
    id: "2",
    productId: "SC-GOD-001",
    sku: "SC-GOD-001",
    name: "Divine Ganesh Stone",
    description: "Bring blessings to your home with this sacred Ganesh stone art. Handcrafted with precision and devotion, featuring intricate traditional artwork. Perfect for spiritual spaces, home temples, or as an auspicious gift. Made from premium black marble.",
    price: 899,
    originalPrice: 1099,
    rating: 4.9,
    reviews: 89,
    bestseller: true,
    category: "God Stone Art",
    image: "https://images.unsplash.com/photo-1545989253-02cc26577f88?w=400&h=400&fit=crop",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Oval"],
    colors: ["Natural Stone", "Black Marble"],
    stock: 35,
    deliveryDays: 7,
    material: "Black Marble",
    weight: "250-600g",
    finish: "Matte",
  },
  {
    id: "3",
    productId: "SC-WEDD-001",
    sku: "SC-WEDD-001",
    name: "Wedding Anniversary Gift",
    description: "Commemorate your special day with this elegant wedding anniversary stone. Features your wedding photo with customizable text and date. Premium white marble with gold leaf accents. A timeless keepsake for your most cherished memories.",
    price: 999,
    originalPrice: 1299,
    rating: 4.7,
    reviews: 67,
    bestseller: false,
    category: "Wedding Gifts",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=400&fit=crop",
    sizes: ["Medium (6x6 inch)", "Large (8x8 inch)", "Extra Large (10x10 inch)"],
    shapes: ["Rectangle", "Heart", "Oval"],
    colors: ["Natural Stone", "White Marble", "Rose Marble"],
    stock: 40,
    deliveryDays: 6,
    material: "White Marble",
    weight: "300-700g",
    finish: "Semi-Gloss",
  },
  {
    id: "4",
    productId: "SC-PET-001",
    sku: "SC-PET-001",
    name: "Pet Memorial Stone",
    description: "Honor your beloved pet with this touching memorial stone. A beautiful way to keep their memory alive forever in your home or garden. Weather-resistant for outdoor placement. Includes paw print design and customizable name.",
    price: 599,
    originalPrice: 799,
    rating: 4.9,
    reviews: 156,
    bestseller: true,
    category: "Pet Memorial",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)"],
    shapes: ["Heart", "Paw Print", "Rectangle"],
    colors: ["Natural Stone", "Black Marble"],
    stock: 60,
    deliveryDays: 5,
    material: "Natural River Stone",
    weight: "200-400g",
    finish: "Natural",
  },
  {
    id: "5",
    productId: "SC-FAM-001",
    sku: "SC-FAM-001",
    name: "Family Photo Stone",
    description: "Capture your family's precious moments on this beautiful stone. Perfect for family reunions, holidays, or as a heartfelt gift. Multi-photo collage option available. Premium quality printing that lasts for generations.",
    price: 799,
    originalPrice: 999,
    rating: 4.8,
    reviews: 92,
    bestseller: false,
    category: "Family Gifts",
    image: "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=400&h=400&fit=crop",
    sizes: ["Medium (6x6 inch)", "Large (8x8 inch)", "Extra Large (10x10 inch)"],
    shapes: ["Rectangle", "Square"],
    colors: ["Natural Stone", "White Marble", "Beige Marble"],
    stock: 45,
    deliveryDays: 6,
    material: "Natural River Stone",
    weight: "250-600g",
    finish: "Glossy",
  },
  {
    id: "6",
    productId: "SC-GOD-002",
    sku: "SC-GOD-002",
    name: "Krishna Stone Art",
    description: "Divine Krishna stone art for spiritual devotion. Features intricate detailing and vibrant colors that bring the deity to life. Traditional Pichwai style artwork on premium stone. Perfect for home temples or spiritual gifting.",
    price: 949,
    originalPrice: 1199,
    rating: 4.9,
    reviews: 78,
    bestseller: true,
    category: "God Stone Art",
    image: "https://images.unsplash.com/photo-1604871000636-074fa5117945?w=400&h=400&fit=crop",
    sizes: ["Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Oval"],
    colors: ["Natural Stone", "Black Marble"],
    stock: 30,
    deliveryDays: 7,
    material: "Black Marble",
    weight: "300-500g",
    finish: "Matte",
  },
  {
    id: "7",
    productId: "SC-CUST-001",
    sku: "SC-CUST-001",
    name: "Custom Name Stone",
    description: "Personalized stone with your name or custom text. Choose from various fonts and styles to create a unique piece that's truly yours. Great for door signs, garden markers, or personalized gifts. UV-resistant printing.",
    price: 499,
    originalPrice: 699,
    rating: 4.6,
    reviews: 54,
    bestseller: false,
    category: "Custom Gifts",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&h=400&fit=crop",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)"],
    shapes: ["Rectangle", "Oval", "Heart"],
    colors: ["Natural Stone", "Black Marble", "White Marble"],
    stock: 100,
    deliveryDays: 4,
    material: "Natural River Stone",
    weight: "150-350g",
    finish: "Natural",
  },
  {
    id: "8",
    productId: "SC-BDAY-001",
    sku: "SC-BDAY-001",
    name: "Birthday Gift Stone",
    description: "Make birthdays unforgettable with this personalized birthday stone. Add the recipient's photo, name, and special message. Colorful confetti design with premium photo quality. A gift that will be cherished forever.",
    price: 649,
    originalPrice: 849,
    rating: 4.7,
    reviews: 43,
    bestseller: false,
    category: "Birthday Gifts",
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=400&fit=crop",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Heart"],
    colors: ["Natural Stone", "White Marble", "Pink Marble"],
    stock: 55,
    deliveryDays: 5,
    material: "Natural River Stone",
    weight: "200-500g",
    finish: "Glossy",
  },
  {
    id: "9",
    productId: "SC-GOD-003",
    sku: "SC-GOD-003",
    name: "Lakshmi Stone Art",
    description: "Goddess Lakshmi stone art for prosperity and blessings. Intricate traditional design with gold accents. Perfect for Diwali, housewarming, or as a spiritual gift. Made from premium white marble with hand-painted details.",
    price: 899,
    originalPrice: 1149,
    rating: 4.8,
    reviews: 62,
    bestseller: true,
    category: "God Stone Art",
    image: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=400&h=400&fit=crop",
    sizes: ["Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Oval"],
    colors: ["Natural Stone", "White Marble"],
    stock: 28,
    deliveryDays: 7,
    material: "White Marble",
    weight: "300-550g",
    finish: "Glossy",
  },
  {
    id: "10",
    productId: "SC-MEM-001",
    sku: "SC-MEM-001",
    name: "Memory Lane Stone",
    description: "Create a timeline of your precious memories with this multi-photo stone. Perfect for graduation, retirement, or milestone celebrations. Can accommodate up to 4 photos with captions. Premium quality archival printing.",
    price: 1199,
    originalPrice: 1499,
    rating: 4.9,
    reviews: 38,
    bestseller: false,
    category: "Custom Gifts",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop",
    sizes: ["Large (8x8 inch)", "Extra Large (10x10 inch)", "Jumbo (12x12 inch)"],
    shapes: ["Rectangle", "Square"],
    colors: ["Natural Stone", "Black Marble", "White Marble"],
    stock: 25,
    deliveryDays: 8,
    material: "Natural River Stone",
    weight: "400-800g",
    finish: "Glossy",
  },
]

export const categories = [
  { id: "couple", name: "Couple Stones", icon: "Heart", description: "Romantic gifts for couples", count: 15 },
  { id: "god", name: "God Stone Art", icon: "Sparkles", description: "Divine spiritual gifts", count: 12 },
  { id: "wedding", name: "Wedding Gifts", icon: "Gift", description: "Perfect for weddings", count: 18 },
  { id: "pet", name: "Pet Memorial", icon: "Heart", description: "Honor your pets", count: 8 },
  { id: "family", name: "Family Gifts", icon: "Users", description: "Family memories", count: 10 },
  { id: "custom", name: "Custom Gifts", icon: "Palette", description: "Fully customizable", count: 20 },
  { id: "birthday", name: "Birthday Gifts", icon: "Cake", description: "Birthday special", count: 14 },
]
