export const products = [
  {
    id: "1",
    productId: "prod-1",
    name: "Romantic Couple Stone",
    description: "Celebrate your love with this beautifully crafted stone featuring your favorite couple photo. Perfect for anniversaries, Valentine's Day, or as a romantic gift.",
    price: 699,
    originalPrice: 899,
    rating: 4.8,
    reviews: 124,
    bestseller: true,
    category: "Couple Stones",
    image: "/images/products/couple-stone.jpg",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Heart"],
    colors: ["Natural Stone", "Black Marble", "White Marble"],
    stock: 50,
    deliveryDays: 5,
  },
  {
    id: "2",
    productId: "prod-2",
    name: "Divine Ganesh Stone",
    description: "Bring blessings to your home with this sacred Ganesh stone art. Handcrafted with precision and devotion, perfect for spiritual spaces or gifting.",
    price: 899,
    originalPrice: 1099,
    rating: 4.9,
    reviews: 89,
    bestseller: true,
    category: "God Stone Art",
    image: "/images/products/ganesh-stone.jpg",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Oval"],
    colors: ["Natural Stone", "Black Marble"],
    stock: 35,
    deliveryDays: 7,
  },
  {
    id: "3",
    productId: "prod-3",
    name: "Wedding Anniversary Gift",
    description: "Commemorate your special day with this elegant wedding anniversary stone. Features your wedding photo with customizable text and date.",
    price: 999,
    originalPrice: 1299,
    rating: 4.7,
    reviews: 67,
    bestseller: false,
    category: "Wedding Gifts",
    image: "/images/products/wedding-gift.jpg",
    sizes: ["Medium (6x6 inch)", "Large (8x8 inch)", "Extra Large (10x10 inch)"],
    shapes: ["Rectangle", "Heart", "Oval"],
    colors: ["Natural Stone", "White Marble", "Rose Marble"],
    stock: 40,
    deliveryDays: 6,
  },
  {
    id: "4",
    productId: "prod-4",
    name: "Pet Memorial Stone",
    description: "Honor your beloved pet with this touching memorial stone. A beautiful way to keep their memory alive forever in your home or garden.",
    price: 599,
    originalPrice: 799,
    rating: 4.9,
    reviews: 156,
    bestseller: true,
    category: "Pet Memorial",
    image: "/images/products/pet-memorial.jpg",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)"],
    shapes: ["Heart", "Paw Print", "Rectangle"],
    colors: ["Natural Stone", "Black Marble"],
    stock: 60,
    deliveryDays: 5,
  },
  {
    id: "5",
    productId: "prod-5",
    name: "Family Photo Stone",
    description: "Capture your family's precious moments on this beautiful stone. Perfect for family reunions, holidays, or as a heartfelt gift.",
    price: 799,
    originalPrice: 999,
    rating: 4.8,
    reviews: 92,
    bestseller: false,
    category: "Family Gifts",
    image: "/images/products/family-stone.jpg",
    sizes: ["Medium (6x6 inch)", "Large (8x8 inch)", "Extra Large (10x10 inch)"],
    shapes: ["Rectangle", "Square"],
    colors: ["Natural Stone", "White Marble", "Beige Marble"],
    stock: 45,
    deliveryDays: 6,
  },
  {
    id: "6",
    productId: "prod-6",
    name: "Krishna Stone Art",
    description: "Divine Krishna stone art for spiritual devotion. Features intricate detailing and vibrant colors that bring the deity to life.",
    price: 949,
    originalPrice: 1199,
    rating: 4.9,
    reviews: 78,
    bestseller: true,
    category: "God Stone Art",
    image: "/images/products/krishna-stone.jpg",
    sizes: ["Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Oval"],
    colors: ["Natural Stone", "Black Marble"],
    stock: 30,
    deliveryDays: 7,
  },
  {
    id: "7",
    productId: "prod-7",
    name: "Custom Name Stone",
    description: "Personalized stone with your name or custom text. Choose from various fonts and styles to create a unique piece that's truly yours.",
    price: 499,
    originalPrice: 699,
    rating: 4.6,
    reviews: 54,
    bestseller: false,
    category: "Custom Gifts",
    image: "/images/products/custom-name.jpg",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)"],
    shapes: ["Rectangle", "Oval", "Heart"],
    colors: ["Natural Stone", "Black Marble", "White Marble"],
    stock: 100,
    deliveryDays: 4,
  },
  {
    id: "8",
    productId: "prod-8",
    name: "Birthday Gift Stone",
    description: "Make birthdays unforgettable with this personalized birthday stone. Add the recipient's photo, name, and special message.",
    price: 649,
    originalPrice: 849,
    rating: 4.7,
    reviews: 43,
    bestseller: false,
    category: "Birthday Gifts",
    image: "/images/products/birthday-stone.jpg",
    sizes: ["Small (4x4 inch)", "Medium (6x6 inch)", "Large (8x8 inch)"],
    shapes: ["Square", "Rectangle", "Heart"],
    colors: ["Natural Stone", "White Marble", "Pink Marble"],
    stock: 55,
    deliveryDays: 5,
  },
]

export const categories = [
  { id: "couple", name: "Couple Stones", icon: "Heart", description: "Romantic gifts for couples", count: 15 },
  { id: "god", name: "God Stone Art", icon: "Sparkles", description: "Divine spiritual gifts", count: 12 },
  { id: "wedding", name: "Wedding Gifts", icon: "Gift", description: "Perfect for weddings", count: 18 },
  { id: "pet", name: "Pet Memorial", icon: "Heart", description: "Honor your pets", count: 8 },
  { id: "family", name: "Family Gifts", icon: "Users", description: "Family memories", count: 10 },
  { id: "custom", name: "Custom Gifts", icon: "Palette", description: "Fully customizable", count: 20 },
  { id: "birthday", name: "Birthday Gifts", icon: "Cake", description: "Birthday special", count: 14 },
]
